### ISSUE TITLE
Content TODO List

### ISSUE THREAD

**Issue by Ablankmann** [Vault-Overseers/nuclear-14#10]
Generic TODO list of basic gameplay stuff we need.

## C# To-Do List
  - [ ]  S.P.E.C.I.A.L System and/or skills and tags. (See @Just-a-Unity-Dev for Skills PR on Frigid).
  - [ ]  Chemical addictions and Fixer drug for removing addiction.
  - [ ]  DamageModifying, and DamageResisting components for Reagents (update 03/01/23 - probably make these status effects)
  - [ ]  Lockpicking Minigame
  - [ ]  Hacking Minigame
  - [ ]  Ranged Hostile NPCs (This will be done by upstream)
  - [ ]  Planetmos (Upstream will do this)
  - [ ]  Day/Night cycle (or way to specify indoors vs outdoor lighting) (Potentially upstream)
  - [ ] NPCs that give quests or lore (talking NPCs can be done now purely in yaml, look at advert component)
  - [ ] NPC stores (whether its vendors or actual NPCs, will need smartvendor UI or the antag store UI).
  - [ ] Computer terminals for writing logs and interacting with machines.

  ## Yaml+ To-Do List
   - [ ] Functioning PipBoy (reskin the PDA UI)
   - [ ] Vending machines for food, robco stuff, drinks, etc etc
   - [ ] Crafting recipes for clothing e.g. hide clothing, backpacks, ghoul skin outfit, makeshift gasmask.
   - [ ] Cooking recipes (feel free to do this as construction graphs as the current cooking system is getting replaced in future).
   - [ ] Botany related stuff for growing in the wasteland and in the vault (reskin hydroponics tray to look like an actual tray ala Rimworld, add the seeds and produce for fallout related plants).
   - [ ] Partial and fully grown plants for harvesting in the wastes (native PNW plants, plus nuts, roots, broc etc).
   - [ ] equipment lockers for factions and loot equivalents for wastes with worse probabilities.
   - [ ] Technology related stuff for brotherhood and vault to get on with (be wary of this too, it could get replaced in future when proper science is added).
   - [ ] Create scavenging options based on the asteroid rock (piles of junk etc).
   - [ ] Alcolohic drinks (reagents, bottles and empty bottles)(rot gut, Gwinnett stout, ale, pale, brew, lager, pilsner, whiskey, wine, rare whiskey and wine, gamma gulp beer, roentgen rum, alcohol-z, moonshine, scotch, vodka, absinthe, rum and nuka, beantown brown beer, bourbon, 
   - [ ] Ghouls as a species.
   - [ ] Super Mutants as a species.
   - [ ] Brahmin and Mutated Chickens as domesticated animals.
   - [ ] Gecko variants.
   - [ ] Replace secway with a scrap motorbike.
   - [ ] Multi tile vehicles such as a van, people carrier (APC) and car. Right click to enter. Has storage.
- [ ] Radios that cycle through a selection of songs, either streamed or uploaded.

## S.P.E.C.I.A.L system related features
   - [ ]  Clothing affecting SPECIAL / Skills
   - [ ]  Have special / skills affect gameplay such as better dice rolls on actions.
   - [ ]  Have certain chems affect certain SPECIAL Stats in positive and negative ways.
   - [ ]  Low INT forces an accent on you.
   - [ ]  Luck affecting loot chances.
   - [ ] Perception affecting accuracy?

**Comment by Just-a-Unity-Dev** [comment]
can low INT just make you sound like a drunk person

**Comment by Veritius** [comment]
Why would SPECIAL be necessary? This is a multiplayer sandbox game, not a linear RPG. I can't see how it would fit.

**Comment by Peptide90** [comment]
> Why would SPECIAL be necessary? This is a multiplayer sandbox game, not a linear RPG. I can't see how it would fit.

We discussed this on discord, essentially it'll allow some variation on character builds that affect skills. Even round to round it can be fun that everyone is different in different ways.

**Comment by Peptide90** [comment]
Updated this issue to better segregate the todo list into stuff new contributors can do (yaml+) and the stuff for C# coders.

**Comment by Peptide90** [comment]
refer to the project page for these issues now.

https://github.com/orgs/Vault-Overseers/projects/1/views/1
