### ISSUE TITLE
The Big Reset ToDo List

### ISSUE THREAD

**Issue by Peptide90** [Vault-Overseers/nuclear-14#168]
## Description

So I'm reseting the codebase to upstream as of todays commit.

To save my sanity instead of cherry picking every commit we ever had over the past 2 years I'm copying over all relevant resources files. This means NO CODE will be transferred over, as its the code portions that are outdated and hard to maintain by myself.

As such below is a list of things that were a casualty of the move and in another list, everything that would be nice to be fixed and any relevant information I can find.

### Casualties

- The wave gamemode.
- Vault gamemodes and objectives.
- Stats / Skills
- TimedStoageFill
- Biome Stuff
- Elevators and ladders

### Things to fix

- [x] Biome stuff - Necessary for the procgen map.
- [x] Stats / Skills - Necessary for the roleplay gamemode. Search for `ClothingSpecialModifier` in Head and OuterClothing as well as check `prototypes/nuclear14/special` and `# TODO:RESET:STATS`
- [x] TimeStorageFill - Necessary. This is broken because of ServerStorageComponent being killed [here](https://github.com/space-wizards/space-station-14/pull/19682/files). Hopefully this helps someone change it to shared. Once this is fixed you can do a search for `# TODO:RESET:TIMEDSTORAGEFILL` to find all relevant commented out entities.
- [x] Wave Gamemode - Would be nice to have for people to play optionally, but by no means a priority right now. Once this is fixed you can do a search for `# TODO:RESET:WAVEDEFENCE` to find all relevant commented out entities.
- [x] Elevators and ladders - Necessary for good maps. `# TODO:RESET:WAVEDEFENCE`

There may be more code related stuff I missed but this is a 2 year old codebase now near enough and it's hard to track.
