### ISSUE TITLE
QoL 4 checklist

### ISSUE THREAD

**Issue by Peptide90** [Vault-Overseers/nuclear-14#333]
- [ ] stun baton crafting
- [ ] Add Breaker (apc) construction.
- [ ] some chair construction.
- [ ] Some wall construction?
- [ ] Grave construction.
- [ ] Add Torch crafting and change the construction graph for wall torches to use them.
- [ ] Add a reskinned kvas type cart for transporting reagents.
- [ ] Add friendly molerat and dog mobs.
- [ ] Ultra stimak used sprite.
- [ ] change composting to compost box mixer
- [ ] Fix cooked gecko sprite. Add entities for all other cooking
- [ ] Sunset sarsparilla, vim and nuka cola crates.
- [ ] Add construction for water vats.
- [ ] Add basalt random ores
- [ ] noSpawn the upstream ores.
- [ ] Make water vats and stuff refillable and give it set transfer amount?
- [ ] Add thirst damage.
- [ ] Add telecoms server resprite
- [ ] Add communications console resprite
- [ ] Make high damage resistance set for blast doors and such
