### ISSUE TITLE
Roadmap to Initial Launch

### ISSUE THREAD

**Issue by Peptide90** [Vault-Overseers/nuclear-14#5]
## Description

This is a basic roadmap to the changes needed to get the minimum viable product out the door and launch the server. Largely this ties into #2 and involves respriting and porting of content. 

Not everything here is required but a lot of them are easy low hanging fruit, and are needed in the long run so it's a list of things for people to pick from.

All changes should go in the Nuclear14 folder then resources or textures, and shouldn't alter the original files. Make a new base item if possible to inherit.

### Entities
- [x] Change gun sprites to Fallout
- [x] Change melee weapons to Fallout
- [x] Change medical items to match Fallout lore
- [x] Add fallout friendly clothing from forks - make sure there's clean and dirty / torn variants
- [x] Replace hardsuits with power armor
- [x] Replace food and drinks with Fallout lore friendly stuff
- [x] Replace tool sprites with https://github.com/space-wizards/space-station-14/pull/8815 and alter where necessary
- [ ] Make rocks that spawn radioactive gas (possibly look at miners for ideas?)
- [x] Radioactive barrels (Currently working on this).
- [ ] Vault walls and working vault door.

### Roles & Mobs

- [x] Add basics roles for each faction.
- [x] Sort loadouts for basic roles
- [ ] Add basic AI mobs both hostile and domesticated
- [ ] Radroach reskin for space tick
- [ ] molerats and giant rats

### Map

- [ ] New Vault map split across multiple levels to use the new ladder system. (Bottom Engi / Sci, Middle dorms / service, top security + entrance?)

### Gameplay Related

- [x] Add a round start experiment "objective" for the Vault Overseer that's randomised from a list.
- [ ] Add durability both on a time based decay and a use based decay. This will make structures break down without repair and items / weapons break down with use.
- [ ] Adapt suspicion into the vault setting?
- [ ] Add some Fallout based events that can specifically affect the vault. Possibly a way to target whitelist certain maps for certain events so they won't affect the wasteland and vice versa. 
- [ ] Bool for announcing events or not and only announcing to affected grids? (Upstream could probably use this for multi station).
- [ ] Ambient music from original games (Have the audio files, Ike was looking to fix ambient sound systems...not essential but would be very nice to have).
- [ ] Botany for the vault (Partly done with produce, just need to do seeds etc).
- [ ] Move as much as possible that players will see from SS14 sprites to Fallout sprites.

### Settings Related

- [x] Adds Fallout related lobby art (pending upstream change to how attribution is handled).
- [x] Forcemap Fallout.
- [ ] Disable fastmos, go back to slow moving gas clouds.

I'll add to this when I get some more time.

**Comment by Peptide90** [comment]
Note to self, consolidate features from this list into the other content To-Do list, then convert this into a MVP list for Vault / Vault+ Launch and link to milestones?

(Vault+ being Vault, plus basic surrounding wasteland for vault dwellers to interact with, no other factions besides possibly raiders as a vault raid "gamemode".

**Comment by Peptide90** [comment]
Closing as most of these are now done. Refer to the project page for all outstanding content to do.
https://github.com/orgs/Vault-Overseers/projects/1/views/1
