### ISSUE TITLE
TODO compendium

### ISSUE THREAD

**Issue by Peptide90** [Vault-Overseers/nuclear-14#62]
## Description

A list of TODOs both from PRs and from code comments. 

This is stuff left out of an original PR due to time, complexity or lacking other features and have been made "TODO" in order to get the PR out and not feature creep and delay PRs.

- [ ] PR 55 - Unused chem sprites that need entities made up for.` berserkpowder, bitterdrink, healingpowder, healingpoultice, hydra, traumapack, mourningpoultice`
- [ ] PR 61 - Add fusion generator ambient sound and visualiser for fusion core / power. Fusion core should be removable.
- [ ] PR 29 - Crafting based cooking, more anti-rad products like charcoal, medical crafting (mortar / pestil stuff), more vendors. Mob butchering and hides.
